### ISSUE TITLE
Lỗi khi chạy demo

### ISSUE THREAD

**Issue by hieucnt** [phamvanhanh6720/IDCardVNRecognition#5]
em cài đầy đủ thư viện và chạy demo thì xuất hiện lỗi này, anh cho em cách khắc phục được k ạ. Em cảm ơn ạ

hieu@hieu-X510UQR:~/Desktop/IDCardVNRecognition$ python3 run.py
ENV is set to: production
2020-10-18 19:02:29.610328: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/home/hieu/Desktop/IDCardVNRecognition/app/__init__.py", line 10, in <module>
    from app import main
  File "/home/hieu/Desktop/IDCardVNRecognition/app/main.py", line 33, in <module>
    reader = Predictor(config)
  File "/home/hieu/Desktop/IDCardVNRecognition/reader/reader.py", line 14, in __init__
    model, vocab = build_model(config)
  File "/home/hieu/.local/lib/python3.6/site-packages/vietocr/tool/translate.py", line 111, in build_model
    config['transformer'])
  File "/home/hieu/.local/lib/python3.6/site-packages/vietocr/model/transformerocr.py", line 13, in __init__
    self.cnn = CNN(backbone, **cnn_args)
  File "/home/hieu/.local/lib/python3.6/site-packages/vietocr/model/cnn.py", line 15, in __init__
    self.model = vgg.vgg19_bn(**kwargs)
TypeError: vgg19_bn() got an unexpected keyword argument 'pretrained'

**Comment by phamvanhanh6720** [comment]
Bạn upgrade vietocr lên 0.3.2

**Comment by hieucnt** [comment]
![image](https://user-images.githubusercontent.com/46702831/97185657-e6f02180-17d2-11eb-88af-5903a81661ec.png)
Em update rồi ạ nhưng vẫn bị lỗi như này ạ. Anh xem giúp em với ạ.
hieu@hieu-X510UQR:~/Desktop/IDCardVNRecognition$ python3 run.py
ENV is set to: production
2020-10-26 21:32:14.433171: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
File exists: /home/hieu/.cache/gdown/https-COLON--SLASH--SLASH-drive.google.com-SLASH-uc-QUESTION-export-EQUAL-download&id-EQUAL-1-olev206xLgXYf7rnwHrcZLxxLg5rs0p
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/home/hieu/Desktop/IDCardVNRecognition/app/__init__.py", line 10, in <module>
    from app import main
  File "/home/hieu/Desktop/IDCardVNRecognition/app/main.py", line 33, in <module>
    reader = Predictor(config)
  File "/home/hieu/Desktop/IDCardVNRecognition/reader/reader.py", line 22, in __init__
    model.load_state_dict(torch.load(weights, map_location=torch.device(device)))
  File "/home/hieu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VietOCR:
        size mismatch for transformer.embed_tgt.weight: copying a param with shape torch.Size([232, 256]) from checkpoint, the shape in current model is torch.Size([233, 256]).
        size mismatch for transformer.fc.weight: copying a param with shape torch.Size([232, 256]) from checkpoint, the shape in current model is torch.Size([233, 256]).
        size mismatch for transformer.fc.bias: copying a param with shape torch.Size([232]) from checkpoint, the shape in current model is torch.Size([233]).
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Em đang cần chạy demo này trên máy cá nhận để làm bài tập làm quen với deep learning, anh cho em xin email để em tiện trao đổi được không ạ. Em cảm ơn anh nhiều ạ !
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
